# Generated by Django 3.2 on 2021-05-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_report_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Patient',
        ),
    ]
