# Generated by Django 3.2 on 2021-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_profile_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='residence',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='l_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='m_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default='smaple@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='password', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
